### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by charlesofkastrup** [aaryankotharii/Corona-Widget#2]
I have tried to build it with Xcode 12 (having made no changes) and there are 5 build errors, the first of which is:

/Corona Widget/Widget/Widget/Widget.swift:13:8: Type 'DataProvider' does not conform to protocol 'TimelineProvider'

I am guessing the code is out of date?

**Comment by aaryankotharii** [comment]
yes @charlesofkastrup thank you for pointing these out!
This was made using Xcode 12.0 beta 2 and apple has made some minor changes since then.
I will be fixing this issue along with #1 in a few hours.
you will be notified once the changes are merged.

**Comment by charlesofkastrup** [comment]
OK, sounds good! Thanks.
