### ISSUE TITLE
Feat: format all numbers with commas.

### ISSUE THREAD

**Issue by aaryankotharii** [aaryankotharii/Corona-Widget#4]
**Is your feature request related to a problem? Please describe.**
With covid-19 cases at an all time high and a total of 34M worldwide cases ( at time of writing ), It gets difficult to read the such large numbers in widgets.

**Describe the solution you'd like**
The numbers should be well formatted with commas at every thousandth place. This makes interpretation easier and improves user experience.  
eg: 987654321 -> 987,654,321

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by Ravi61** [comment]
Raised https://github.com/aaryankotharii/Corona-Widget/pull/5 @aaryankotharii
