### ISSUE TITLE
bug: largeWidget fix padding

### ISSUE THREAD

**Issue by aaryankotharii** [aaryankotharii/Corona-Widget#7]
**Describe the bug**
The large widget has first 4 rows too close and the following 3 with greater padding.

**To Reproduce**
1. Add large widget to your homescreen.
2. view bug.

**Expected behavior**
The padding throughout the widget should  be uniform.

**Testing (please complete the following information):**
 - Device: iPhone 11
 - iOS: 14.0
 - Xcode: 12.6 beta

**Comment by devanshimodha** [comment]
Please check the PR

Have resolved this

**Comment by aaryankotharii** [comment]
Hey @devanshimodha, I have not received a pr for this.
could you please check again?

**Comment by devanshimodha** [comment]
@aaryankotharii do you need the image (confirmed, recovered, and death) in the large widget as the numbers are not visible in smaller devices then?

**Comment by devanshimodha** [comment]
@aaryankotharii Let me know if you have received the PR now

**Comment by aaryankotharii** [comment]
fixed in #10.
